version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:16.2
    restart: always
    env_file: .env
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # localhost:container
    ports:
      - '5430:5432'
    volumes:
      - ./volumes/data:/data/db
  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # localhost:container
    ports:
      - '3001:3000'
    depends_on:
      - postgres
