services:
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=hux
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@admin
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/data:/data/db
  # redis:
  #   container_name: redis-container
  #   image: redis/redis-stack-server:latest
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --loglevel warning
  #   volumes:
  #     - ./volumes/cache:/data
  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      # - redis
